<?php
/**
 * loading.php — Loading screen shown on first page visit
 */
?>
<div id="loading-screen" role="status" aria-label="Loading">
    <div class="loading-content">
        <!-- Animated particle dots (generated by JS) -->
        <div class="loading-particles" id="loadingParticles"></div>

        <!-- Spinning orbital rings -->
        <div class="loading-orb"></div>

        <!-- Letter-by-letter "WELCOME" text -->
        <div class="loading-text" id="loadingText">
            <?php foreach (str_split('WELCOME') as $letter): ?>
                <span><?php echo $letter; ?></span>
            <?php endforeach; ?>
        </div>

        <!-- Progress bar -->
        <div class="progress-bar">
            <div class="progress-fill"></div>
        </div>
    </div>
</div>
